export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";

export const UPDATE_LOCATION = "UPDATE_LOCATION";

export const UPDATE_INPUT= 'UPDATE_INPUT';
export const INITIALIZE_INPUT= 'INITIALIZE_INPUT';

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS= "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SEND_EMAIL = "AUTH_SEND_EMAIL";
export const AUTH_CLEAR_EMAIL = "AUTH_CLEAR_EMAIL";
export const AUTH_VERIFY = "AUTH_VERIFY";
export const AUTH_CLAER_ERROR = "AUTH_CLAER_ERROR";
export const AUTH_RESET_PASSWORD = "AUTH_RESET_PASSWORD";
export const AUTH_UPDATE_ME = "AUTH_UPDATE_ME";
export const AUTH_UPDATE_SUCCESS = "AUTH_UPDATE_SUCCESS";
export const AUTH_CANCEL_SUCCESS = "AUTH_CANCEL_SUCCESS"
export const AUTH_BOOKMARK_SUCCESS = "AUTH_BOOKMARK_SUCCESS";
export const AUTH_CLAER_MESSAGE = "AUTH_CLAER_MESSAGE"


export const ROOM_START = "ROOM_START";
export const ROOM_CREATE = "ROOM_CREATE";
export const ROOM_SUCCESS = "ROOM_SUCCESS";
export const ROOM_CREATE_SUCCESS = "ROOM_CREATE_SUCCESS";
export const ROOM_UPDATE_SUCCESS = "ROOM_UPDATE_SUCCESS";
export const ROOM_FAIL ="ROOM_FAIL";
export const FETCH_ROOMS ="FETCH_ROOMS";
export const ADD_ROOM = "ADD_ROOM"
export const SELECT_ROOM = "SELECT_ROOM";
export const CLEAR_ROOMS = "CLEAR_ROOMS";
export const CLEAR_ROOM_ERROR = "CLEAR_ROOM_LOADER"

export const MESSAGE_START = "MESSAGE_START";
export const MESSAGE_SUCCESS = "MESSAGE_SUCCESS";
export const MESSAGE_FAIL ="MESSAGE_FAIL";
export const MESSAGE_CREATE_SUCCESS = "MESSAGE_CREATE_SUCCESS";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGE"

