import React from "react";
import Aux from "../../hoc/Aux/Aux";

export const langugaeOptions = (
            <Aux>
                <option value="Any">Any language</option>
                <option value="Abkhazian">Abkhazian</option>
                <option value="Achinese">Achinese</option>
                <option value="Acoli">Acoli</option>
                <option value="Adangme">Adangme</option>
                <option value="Adyghe">Adyghe</option>
                <option value="Afar">Afar</option>
                <option value="Afrihili">Afrihili</option>
                <option value="Afrikaans">Afrikaans</option>
                <option value="Afro-Asiatic">Afro-Asiatic languages</option>
                <option value="Ainu">Ainu</option>
                <option value="Akan">Akan</option>
                <option value="Akkadian">Akkadian</option>
                <option value="Albanian">Albanian</option>
                <option value="Aleut">Aleut</option>
                <option value="Algonquian">Algonquian languages</option>
                <option value="Altaic languages">Altaic languages</option>
                <option value="Amharic">Amharic</option>
                <option value="Angika">Angika</option>
                <option value="Apache languages">Apache languages</option>
                <option value="Arabic">Arabic</option>
                <option value="Aragonese">Aragonese</option>
                <option value="Arapaho">Arapaho</option>
                <option value="Arawak">Arawak</option>
                <option value="Armenian">Armenian</option>
                <option value="Aromanian arumanian macedo-romanian">Aromanian Arumanian Macedo-Romanian</option>
                <option value="Artificial languages">Artificial languages </option>
                <option value="Assamese">Assamese</option>
                <option value="Asturian bable leonese asturleonese">Asturian Bable Leonese Asturleonese</option>
                <option value="Athapasca languages">Athapascan languages </option>
                <option value="Australian languages">Australian languages</option>
                <option value="Austronesian languages">Austronesian languages</option>
                <option value="Avaric">Avaric</option>
                <option value="Avestan">Avestan</option>
                <option value="Awadhi">Awadhi</option>
                <option value="Aymara">Aymara</option>
                <option value="Azerbaijani">Azerbaijani</option>
                <option value="Balinese">Balinese</option>
                <option value="Baltic languages">Baltic languages</option>
                <option value="Baluchi">Baluchi</option>
                <option value="Bambara">Bambara</option>
                <option value="Bamileke languages">Bamileke languages</option>
                <option value="Banda languages">Banda languages</option>
                <option value="Basa">Basa</option>
                <option value="Bashkir">Bashkir</option>
                <option value="Basque">Basque</option>
                <option value="Batak languages">Batak languages</option>
                <option value="Beja bedawiyet">Beja Bedawiyet</option>
                <option value="Belarusian">Belarusian</option>
                <option value="Bemba">Bemba</option>
                <option value="Bengali">Bengali</option>
                <option value="Berber languages">Berber languages</option>
                <option value="Bhojpuri">Bhojpuri </option>
                <option value="Bihari languages">Bihari languages</option>
                <option value="Bikol">Bikol</option>
                <option value="Bini edo">Bini Edo</option>
                <option value="Bislama">Bislama</option>
                <option value="Blin bilin">Blin Bilin</option>
                <option value="Blissymbols blissymbolics bliss">Blissymbols Blissymbolics Bliss </option>
                <option value="Bokmål">Bokmål</option>
                <option value="Bosnian">Bosnian</option>
                <option value="Braj">Braj</option>
                <option value="Breton">Breton</option>
                <option value="Buginese">Buginese</option>
                <option value="Bulgarian">Bulgarian</option>
                <option value="Buriat">Buriat</option>
                <option value="Burmese">Burmese</option>
                <option value="Caddo">Caddo</option>
                <option value="Catalan valencian">Catalan Valencian</option>
                <option value="Caucasian languages">Caucasian languages</option>
                <option value="Cebuano">Cebuano</option>
                <option value="Celtic languages">Celtic languages</option>
                <option value="Central american indian languages">Central American Indian languages</option>
                <option value="Central khmer">Central Khmer</option>
                <option value="Chagatai">Chagatai</option>
                <option value="Chamic languages">Chamic languages</option>
                <option value="Chamorro">Chamorro</option>
                <option value="Chechen">Chechen</option>
                <option value="Cherokee">Cherokee</option>
                <option value="Cheyenne">Cheyenne</option>
                <option value="Chibcha">Chibcha</option>
                <option value="Chichewa chewa nyanja">Chichewa Chewa Nyanja</option>
                <option value="Chinese">Chinese</option>
                <option value="Chinook jargon">Chinook jargon</option>
                <option value="Chipewyan dene suline">Chipewyan Dene Suline</option>
                <option value="Choctaw">Choctaw</option>
                <option value="Church slavic old slavonic church bulgarian">Church Slavic Old Slavonic Church Slavonic Old Bulgarian Old Church Slavonic</option>
                <option value="Chuukese">Chuukese</option>
                <option value="Chuvash">Chuvash</option>
                <option value="Classical newari old classical nepal bhasa">Classical Newari Old Newari Classical Nepal Bhasa</option>
                <option value="Classical syriac">Classical Syriac</option>
                <option value="Coptic">Coptic</option>
                <option value="Cornish">Cornish</option>
                <option value="Corsican">Corsican</option>
                <option value="Cree">Cree</option>
                <option value="Creek">Creek</option>
                <option value="Creoles and pidgins">Creoles and pidgins</option>
                <option value="Crimean tatar crimean turkish">Crimean Tatar Crimean Turkish</option>
                <option value="Croatian">Croatian</option>
                <option value="Cushitic languages">Cushitic languages</option>
                <option value="Czech">Czech</option>
                <option value="Dakota">Dakota</option>
                <option value="Danish">Danish</option>
                <option value="Dargwa">Dargwa</option>
                <option value="Delaware">Delaware</option>
                <option value="Dinka">Dinka</option>
                <option value="Divehi dhivehi maldivian">Divehi Dhivehi Maldivian</option>
                <option value="Dogri">Dogri</option>
                <option value="Dogrib">Dogrib</option>
                <option value="Dravidian languages">Dravidian languages</option>
                <option value="Duala">Duala</option>
                <option value="Dutch">Dutch</option>
                <option value="Dutch flemish">Dutch Flemish</option>
                <option value="Dyula">Dyula</option>
                <option value="Dzongkha">Dzongkha</option>
                <option value="Eastern frisian">Eastern Frisian</option>
                <option value="Efik">Efik</option>
                <option value="Ekajuk">Ekajuk</option>
                <option value="Elamite">Elamite</option>
                <option value="English">English</option>
                <option value="Erzya">Erzya</option>
                <option value="Esperanto">Esperanto</option>
                <option value="Estonian">Estonian</option>
                <option value="Ewe">Ewe</option>
                <option value="Ewondo">Ewondo</option>
                <option value="Fang">Fang</option>
                <option value="Fanti">Fanti</option>
                <option value="Faroese">Faroese</option>
                <option value="Fijian">Fijian</option>
                <option value="Filipino pilipino">Filipino Pilipino</option>
                <option value="Finnish">Finnish</option>
                <option value="Finno-Ugrian languages">Finno-Ugrian languages</option>
                <option value="Fon">Fon</option>
                <option value="French">French</option>
                <option value="Friulian">Friulian</option>
                <option value="Fulah">Fulah</option>
                <option value="Ga">Ga</option>
                <option value="Gaelic scottish gaelic">Gaelic Scottish Gaelic </option>
                <option value="Galibi carib">Galibi Carib</option>
                <option value="Galician">Galician</option>
                <option value="Ganda">Ganda</option>
                <option value="Gayo">Gayo</option>
                <option value="Gbaya">Gbaya</option>
                <option value="Geez">Geez</option>
                <option value="Georgian">Georgian</option>
                <option value="German">German</option>
                <option value="Germanic languages">Germanic languages</option>
                <option value="Gilbertese">Gilbertese</option>
                <option value="Gondi">Gondi</option>
                <option value="Gorontalo">Gorontalo</option>
                <option value="Gothic">Gothic</option>
                <option value="Grebo">Grebo</option>
                <option value="Greek">Greek</option>
                <option value="Guarani">Guarani</option>
                <option value="Gujarati">Gujarati</option>
                <option value="Gwich'in">Gwich'in</option>
                <option value="Haida">Haida</option>
                <option value="Haitian haitian creole">Haitian Haitian Creole</option>
                <option value="Hausa">Hausa</option>
                <option value="Hawaiian">Hawaiian</option>
                <option value="Hebrew">Hebrew</option>
                <option value="Herero">Herero</option>
                <option value="Hiligaynon">Hiligaynon</option>
                <option value="Himachali languages western pahari">Himachali languages Western Pahari languages</option>
                <option value="Hindi">Hindi</option>
                <option value="Hiri motu">Hiri Motu</option>
                <option value="Hittite">Hittite</option>
                <option value="Hmong mong">Hmong Mong </option>
                <option value="Hungarian">Hungarian</option>
                <option value="Hupa">Hupa</option>
                <option value="Iban">Iban</option>
                <option value="Icelandic">Icelandic</option>
                <option value="Ido">Ido</option>
                <option value="Igbo">Igbo</option>
                <option value="Ijo languages">Ijo languages</option>
                <option value="Iloko">Iloko</option>
                <option value="Inari sami">Inari Sami</option>
                <option value="Indic languages">Indic languages</option>
                <option value="Indo-European languages">Indo-European languages</option>
                <option value="Indonesian">Indonesian</option>
                <option value="Ingush">Ingush</option>
                <option value="Interlingua">Interlingua</option>
                <option value="Interlingue occidental">Interlingue Occidental</option>
                <option value="Inuktitut">Inuktitut</option>
                <option value="Inupiaq">Inupiaq</option>
                <option value="Iranian languages">Iranian languages</option>
                <option value="Irish">Irish</option>
                <option value="Iroquoian languages">Iroquoian languages</option>
                <option value="Italian">Italian</option>
                <option value="Japanese">Japanese</option>
                <option value="Javanese">Javanese</option>
                <option value="Judeo-Arabic">Judeo-Arabic</option>
                <option value="Judeo-Persian">Judeo-Persian</option>
                <option value="Kabardian">Kabardian</option>
                <option value="Kabyle">Kabyle</option>
                <option value="Kachin jingpho">Kachin Jingpho</option>
                <option value="Kalaallisut greenlandic">Kalaallisut Greenlandic</option>
                <option value="Kalmyk oirat">Kalmyk Oirat</option>
                <option value="Kamba">Kamba</option>
                <option value="Kannada">Kannada</option>
                <option value="Kanuri">Kanuri</option>
                <option value="Kara-Kalpak">Kara-Kalpak</option>
                <option value="Karachay-Balkar">Karachay-Balkar</option>
                <option value="Karelian">Karelian</option>
                <option value="Karen languages">Karen languages</option>
                <option value="Kashmiri">Kashmiri</option>
                <option value="Kashubian">Kashubian</option>
                <option value="Kawi">Kawi</option>
                <option value="Kazakh">Kazakh</option>
                <option value="Khasi">Khasi</option>
                <option value="Khoisan languages">Khoisan languages</option>
                <option value="Khotanese sakan">Khotanese Sakan</option>
                <option value="Kikuyu gikuyu">Kikuyu Gikuyu</option>
                <option value="Kimbundu">Kimbundu</option>
                <option value="Kinyarwanda">Kinyarwanda</option>
                <option value="Kirghiz kyrgyz">Kirghiz Kyrgyz</option>
                <option value="Klingon tlhingan-hol">Klingon tlhIngan-Hol</option>
                <option value="Komi">Komi</option>
                <option value="Kongo">Kongo</option>
                <option value="Konkani">Konkani</option>
                <option value="Korean">Korean</option>
                <option value="Kosraean">Kosraean</option>
                <option value="Kpelle">Kpelle</option>
                <option value="Kru languages">Kru languages</option>
                <option value="Kuanyama kwanyama">Kuanyama Kwanyama </option>
                <option value="Kumyk">Kumyk</option>
                <option value="Kurdish">Kurdish</option>
                <option value="Kurukh">Kurukh</option>
                <option value="Kutenai">Kutenai</option>
                <option value="Ladino">Ladino</option>
                <option value="Lahnda">Lahnda</option>
                <option value="Lamba">Lamba</option>
                <option value="Land dayak languages">Land Dayak languages</option>
                <option value="Lao">Lao</option>
                <option value="Latin">Latin</option>
                <option value="Latvian">Latvian</option>
                <option value="Lezghian">Lezghian</option>
                <option value="Limburgan limburger limburgish">Limburgan Limburger Limburgish</option>
                <option value="Lingala">Lingala</option>
                <option value="Lithuanian">Lithuanian</option>
                <option value="Lojban">Lojban</option>
                <option value="Low german low saxon">Low German Low Saxon German</option>
                <option value="Lower sorbian=">Lower Sorbian</option>
                <option value="Lozi">Lozi</option>
                <option value="Luba-Katanga">Luba-Katanga</option>
                <option value="Luba-Lulua">Luba-Lulua</option>
                <option value="Luiseno">Luiseno</option>
                <option value="Lule sami">Lule Sami </option>
                <option value="Lunda">Lunda</option>
                <option value="Luo">Luo</option>
                <option value="Lushai">Lushai</option>
                <option value="Luxembourgish letzeburgesch">Luxembourgish Letzeburgesch</option>
                <option value="Macedonian">Macedonian</option>
                <option value="Madurese">Madurese</option>
                <option value="Magahi">Magahi</option>
                <option value="Maithili">Maithili</option>
                <option value="Makasar">Makasar</option>
                <option value="Malagasy">Malagasy</option>
                <option value="Malay">Malay</option>
                <option value="Malayalam">Malayalam</option>
                <option value="Maltese">Maltese</option>
                <option value="Manchu">Manchu</option>
                <option value="Mandar">Mandar</option>
                <option value="Mandingo">Mandingo</option>
                <option value="Manipuri">Manipuri</option>
                <option value="Manobo languages">Manobo languages</option>
                <option value="Manx">Manx</option>
                <option value="Maori">Maori</option>
                <option value="Mapudungun mapuche">Mapudungun Mapuche</option>
                <option value="Marathi">Marathi</option>
                <option value="Mari">Mari</option>
                <option value="Marshallese">Marshallese</option>
                <option value="Marwari">Marwari</option>
                <option value="Masai">Masai</option>
                <option value="Mayan languages">Mayan languages</option>
                <option value="Mende">Mende</option>
                <option value="Mi'kmaq micmac">Mi'kmaq Micmac</option>
                <option value="Minangkabau">Minangkabau</option>
                <option value="Mirandese">Mirandese</option>
                <option value="Mohawk">Mohawk</option>
                <option value="Moksha">Moksha</option>
                <option value="Mon-Khmer languages">Mon-Khmer languages</option>
                <option value="Mongo">Mongo</option>
                <option value="Mongolian">Mongolian</option>
                <option value="Mossi">Mossi</option>
                <option value="Multiple languages">Multiple languages</option>
                <option value="Munda languagesn">Munda languagesn</option>
                <option value="N'Ko">N'Ko</option>
                <option value="Nahuatl languages">Nahuatl languages</option>
                <option value="Nauru">Nauru</option>
                <option value="Navajo navaho">Navajo Navaho</option>
                <option value="Ndebele">Ndebele</option>
                <option value="Ndonga">Ndonga</option>
                <option value="Neapolitan">Neapolitan</option>
                <option value="Nepal bhasa newari">Nepal Bhasa Newari</option>
                <option value="Nepali">Nepali</option>
                <option value="Nias">Nias</option>
                <option value="Niger-Kordofanian languages">Niger-Kordofanian languages</option>
                <option value="Nilo-Saharan languages">Nilo-Saharan languages </option>
                <option value="Niuean">Niuean</option>
                <option value="No linguistic content not applicable">No linguistic content Not applicable</option>
                <option value="Nogai">Nogai</option>
                <option value="Norse">Norse</option>
                <option value="North american indian languages">North American Indian languages</option>
                <option value="Northern frisian">Northern Frisian</option>
                <option value="Northern sami">Northern Sami </option>
                <option value="Norwegian">Norwegian</option>
                <option value="Norwegian nynorsk">Norwegian Nynorsk Nynorsk</option>
                <option value="Nubian languages">Nubian languages</option>
                <option value="Nyamwezi">Nyamwezi</option>
                <option value="Nyankole">Nyankole</option>
                <option value="Nyoro">Nyoro</option>
                <option value="Nzima">Nzima</option>
                <option value="Ojibwa">Ojibwa</option>
                <option value="Oriya">Oriya</option>
                <option value="Oromo">Oromo</option>
                <option value="Osage">Osage</option>
                <option value="Ossetian ossetic">Ossetian Ossetic</option>
                <option value="Otomian languages">Otomian languages</option>
                <option value="Pahlavi">Pahlavi</option>
                <option value="Palauan">Palauan</option>
                <option value="Pali">Pali</option>
                <option value="Pampanga kapampangan">Pampanga Kapampangan</option>
                <option value="Pangasinan">Pangasinan</option>
                <option value="Panjabi punjabi">Panjabi Punjabi</option>
                <option value="Papiamento">Papiamento</option>
                <option value="Papuan languages">Papuan languages</option>
                <option value="Pedi sepedi northern sotho">Pedi Sepedi Northern Sotho</option>
                <option value="Persian">Persian</option>
                <option value="Philippine languages">Philippine languages</option>
                <option value="Phoenician">Phoenician</option>
                <option value="Pohnpeian">Pohnpeian</option>
                <option value="Polish">Polish</option>
                <option value="Portuguese">Portuguese</option>
                <option value="Prakrit languages">Prakrit languages </option>
                <option value="Provençal">Provençal</option>
                <option value="Pushto pashto">Pushto Pashto</option>
                <option value="Quechua">Quechua</option>
                <option value="Rajasthani">Rajasthani</option>
                <option value="Rapanui">Rapanui</option>
                <option value="Rarotongan cook islands maori">Rarotongan Cook Islands Maori</option>
                <option value="Reserved for local use">Reserved for local use</option>
                <option value="Romance languages">Romance languages</option>
                <option value="Romanian moldavian moldovan">Romanian Moldavian Moldovan </option>
                <option value="Romansh">Romansh</option>
                <option value="Romany">Romany</option>
                <option value="Rundi">Rundi</option>
                <option value="Russian">Russian</option>
                <option value="Salishan languages">Salishan languages</option>
                <option value="Samaritan aramaic">Samaritan Aramaic</option>
                <option value="Sami languages">Sami languages</option>
                <option value="Samoan">Samoan</option>
                <option value="Sandawe">Sandawe</option>
                <option value="Sango">Sango</option>
                <option value="Sanskrit">Sanskrit</option>
                <option value="Santali">Santali</option>
                <option value="Sardinian">Sardinian</option>
                <option value="Sasak">Sasak</option>
                <option value="Scots">Scots</option>
                <option value="Selkup">Selkup</option>
                <option value="Semitic languages">Semitic languages</option>
                <option value="Serbian">Serbian</option>
                <option value="Serer">Serer</option>
                <option value="Shan">Shan</option>
                <option value="Shona">Shona</option>
                <option value="Sichuan yi nuosu">Sichuan Yi Nuosu</option>
                <option value="Sicilian">Sicilian</option>
                <option value="Sidamo">Sidamo</option>
                <option value="Sign languages">Sign Languages</option>
                <option value="Siksika">Siksika</option>
                <option value="Sindhi">Sindhi</option>
                <option value="Sinhala sinhalese">Sinhala Sinhalese</option>
                <option value="Sino-Tibetan languages">Sino-Tibetan languages</option>
                <option value="Siouan languages">Siouan languages </option>
                <option value="Skolt sami">Skolt Sami</option>
                <option value="Slavic languages">Slavic languages</option>
                <option value="Slovak">Slovak</option>
                <option value="Slovenian">Slovenian</option>
                <option value="Sogdian">Sogdian</option>
                <option value="Somali">Somali</option>
                <option value="Songhai languages">Songhai languages</option>
                <option value="Soninke">Soninke</option>
                <option value="Sorbian languages">Sorbian languages</option>
                <option value="Sotho">Sotho</option>
                <option value="Southern altai">Southern Altai</option>
                <option value="Southern sami">Southern Sami </option>
                <option value="Spanish castilian">Spanish Castilian</option>
                <option value="Sranan tongo">Sranan Tongo</option>
                <option value="Sukuma">Sukuma</option>
                <option value="Sumerian">Sumerian</option>
                <option value="Sundanese">Sundanese</option>
                <option value="Susu">Susu</option>
                <option value="Swahili">Swahili</option>
                <option value="Swati">Swati</option>
                <option value="Swedish">Swedish</option>
                <option value="Swiss german alemannic alsatian">Swiss German Alemannic Alsatian </option>
                <option value="Syriac">Syriac</option>
                <option value="Tagalog">Tagalog</option>
                <option value="Tahitian">Tahitian</option>
                <option value="Tai languages">Tai languages</option>
                <option value="Tajik">Tajik</option>
                <option value="Tamashek">Tamashek</option>
                <option value="Tamil">Tamil</option>
                <option value="Tatar">Tatar</option>
                <option value="Telugu">Telugu</option>
                <option value="Tereno">Tereno</option>
                <option value="Tetum">Tetum</option>
                <option value="Thai">Thai</option>
                <option value="Tibetan">Tibetan</option>
                <option value="Tigre">Tigre</option>
                <option value="Tigrinyar">Tigrinyar</option>
                <option value="Timne">Timne</option>
                <option value="Tiv">Tiv</option>
                <option value="Tlingit">Tlingit</option>
                <option value="Tok pisin">Tok Pisin</option>
                <option value="Tokelau">Tokelau</option>
                <option value="Tonga">Tonga</option>
                <option value="Tsimshian">Tsimshian</option>
                <option value="Tsonga">Tsonga</option>
                <option value="Tswana">Tswana</option>
                <option value="Tumbuka">Tumbuka</option>
                <option value="Tupi languages">Tupi languages</option>
                <option value="Turkish">Turkish</option>
                <option value="Turkmen">Turkmen</option>
                <option value="Tuvalu">Tuvalu</option>
                <option value="Tuvinian">Tuvinian</option>
                <option value="Twi">Twi</option>
                <option value="Udmurt">Udmurt</option>
                <option value="Ugaritic">Ugaritic</option>
                <option value="Uighur uyghur">Uighur Uyghur</option>
                <option value="Ukrainian">Ukrainian</option>
                <option value="Umbundu">Umbundu</option>
                <option value="Uncoded languages">Uncoded languages</option>
                <option value="Undetermined">Undetermined</option>
                <option value="Upper sorbian">Upper Sorbian</option>
                <option value="Urdu">Urdu</option>
                <option value="Uzbek">Uzbek</option>
                <option value="Vai">Vai</option>
                <option value="Venda">Venda</option>
                <option value="Vietnamese">Vietnamese</option>
                <option value="Volapük">Volapük</option>
                <option value="Votic">Votic</option>
                <option value="Wakashan languages">Wakashan languages</option>
                <option value="Walamo">Walamo</option>
                <option value="Walloon">Walloon</option>
                <option value="Waray">Waray</option>
                <option value="Washo">Washo</option>
                <option value="Welsh">Welsh</option>
                <option value="Western frisian">Western Frisian</option>
                <option value="Wolof">Wolof</option>
                <option value="Xhosa">Xhosa</option>
                <option value="Yakut">Yakut</option>
                <option value="Yao">Yao</option>
                <option value="Yapese">Yapese</option>
                <option value="Yiddish">Yiddish</option>
                <option value="Yoruba">Yoruba</option>
                <option value="Yupik languages">Yupik languages</option>
                <option value="Zande languages">Zande languages</option>
                <option value="Zapotec">Zapotec</option>
                <option value="Zaza dimili dimli kirdki kirmanjki zazaki">Zaza Dimili Dimli Kirdki Kirmanjki Zazaki</option>
                <option value="Zenaga">Zenaga</option>
                <option value="Zhuang chuang">Zhuang Chuang </option>
                <option value="Zulu">Zulu</option>
                <option value="Zuni">Zuni</option>
            </Aux>
)